### PR TITLE
Ui automator tests 41

### PR DESCRIPTION
**Pull request by hasan-ahmed**
This PR relates to issue #41. 

- searchForResizeableTest : finds the scrollable ListView in the widgets and scrolls to the end to validate that we have a scrollable stock list.

- defaultStockListTest: this test scrolls through the list of stock displayed in the widget to assure that all the stocks on the default developer stock list are shown.

### CODE REVIEW

**Comment by hasan-ahmed** [comment]
@karlogonzales UI Automator requires android 18 so we can't have UI Automation tests if we change that. 

I'm working on making travis work.

**Comment by karlogonzales** [comment]
@hasan-ahmed Ah ok well just make sure that nothing else breaks when the min sdk is increased

**Comment by hasan-ahmed** [comment]
we need to change **./gradlew connectedCheck** to **./gradlew test** because "connectedCheck" runs instrumentation tests (such as UI Automator tests) that fail travis because it looks for a connected device. It wasn't a problem until now because we didn't have instrumentation tests but we do now. 
 changed it for the API 25 but we need to do it for all the new stages we added.

**Comment by karlogonzales** [comment]
It worked on that API build even before. The problem is that we need the other API builds to get marks. If you put the other API tests back does it work?

**Comment by hasan-ahmed** [comment]
@karlogonzales we can keep all the API builds but just change ./gradlew connectedCheck to ./gradlew test so that we run all the unit tests but ignore UI Automator tests in travis

**Comment by hasan-ahmed** [comment]
screen shot 2018-03-16 at 8 16 55 pm
 
Actually this is really weird. connectedCheck is being run even though I just changed it to test.

**Comment by hasan-ahmed** [comment]
Travis is passing now

**Comment by karlogonzales** [comment]
# Note before you commit make sure that the application still runs as intended 
Ill test right now

**Pull request merged**
